<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Conductor;

class ConductoresSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
[ 'nombres' => 'José', 'apellidos' => 'Córdoba arbelaez', 'cedula' => '7254549', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'SPW468', 'numero_interno' => '793', 'celular' => '3106155909', 'correo' => 'Josecordova0280@gmail.com', 'fecha_nacimiento' => '1980-02-21', 'otra_profesion' => 'No', 'nivel_estudios' => '' ],
[ 'nombres' => 'Diego Alexander', 'apellidos' => 'Rincón montoya', 'cedula' => '1002731462', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'SAV507', 'numero_interno' => '770', 'celular' => '3217629520', 'correo' => 'No tiene', 'fecha_nacimiento' => '2001-03-28', 'otra_profesion' => 'Oficios varios', 'nivel_estudios' => '' ],
[ 'nombres' => 'Guillermo', 'apellidos' => 'Hoyos Suarez', 'cedula' => '10101967', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'TJV957', 'numero_interno' => '780', 'celular' => '3108904882', 'correo' => 'No tiene', 'fecha_nacimiento' => '1966-01-03', 'otra_profesion' => 'No', 'nivel_estudios' => '' ],
[ 'nombres' => 'Camilo Andrés', 'apellidos' => 'León aristizabal', 'cedula' => '1193200799', 'conductor_tipo' => 'A', 'rh' => 'O-', 'vehiculo_placa' => 'SKM666', 'numero_interno' => '739', 'celular' => '3218539639', 'correo' => 'camilo2327@icloud.com', 'fecha_nacimiento' => '2003-06-23', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'José Jair', 'apellidos' => 'Gonzales Cardona', 'cedula' => '15988328', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'WOV287', 'numero_interno' => '760', 'celular' => '3218802226', 'correo' => 'gonzalesjair1970@gmail.com', 'fecha_nacimiento' => '1974-09-03', 'otra_profesion' => 'No', 'nivel_estudios' => 'Hasta primaria' ],
[ 'nombres' => 'Héctor welman', 'apellidos' => 'Jaramillo', 'cedula' => '16162045', 'conductor_tipo' => 'A', 'rh' => 'B+', 'vehiculo_placa' => 'WMB411', 'numero_interno' => '752', 'celular' => '3215941298', 'correo' => 'welman0785@gmail.com', 'fecha_nacimiento' => '1985-07-22', 'otra_profesion' => 'Mecánico automotriz', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'Julian Andres', 'apellidos' => 'Castañeda lopera', 'cedula' => '1053769083', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'RELEVO', 'numero_interno' => 'Relevo', 'celular' => '3113775907', 'correo' => 'jandrescastalopera@hotmail.com', 'fecha_nacimiento' => '1986-06-07', 'otra_profesion' => 'Oficios varios', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'Daniel Andrés', 'apellidos' => 'Cruz clavijo', 'cedula' => '4438177', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'STR013', 'numero_interno' => '783', 'celular' => '3186557390', 'correo' => 'danicruz1383@gmail.com', 'fecha_nacimiento' => '1983-12-13', 'otra_profesion' => 'Oficios varios', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'Olver', 'apellidos' => 'Cifuentes buitrago', 'cedula' => '16114903', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'KZW588', 'numero_interno' => '791', 'celular' => '3232337851', 'correo' => 'No tiene', 'fecha_nacimiento' => '1982-08-12', 'otra_profesion' => 'No', 'nivel_estudios' => 'Hasta primaria' ],
[ 'nombres' => 'Tulio Edgardo', 'apellidos' => 'Alarcón Cuéllar', 'cedula' => '6349842', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'SVM611', 'numero_interno' => '734', 'celular' => '3232213931', 'correo' => 'tulioalarcon1957@gmail.com', 'fecha_nacimiento' => '1957-03-27', 'otra_profesion' => 'Mecánica básica', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'Germán Andrés', 'apellidos' => 'Olaya Pérez', 'cedula' => '1054552024', 'conductor_tipo' => 'B', 'rh' => 'A+', 'vehiculo_placa' => 'VIK537', 'numero_interno' => '1045', 'celular' => '3233793575', 'correo' => 'germanandresolaya1990gmail.com', 'fecha_nacimiento' => '1990-03-27', 'otra_profesion' => 'Barbero', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'Ezequiel', 'apellidos' => 'Peñaloza silva', 'cedula' => '14322687', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'WMZ597', 'numero_interno' => '746', 'celular' => '3142121647', 'correo' => 'duvan11301972@gmail.com', 'fecha_nacimiento' => '1972-11-30', 'otra_profesion' => 'Oficios varios', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'Otto Mario', 'apellidos' => 'Mejía alape', 'cedula' => '71481782', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'NNN981', 'numero_interno' => '800', 'celular' => '3128609032', 'correo' => 'marioalape79@gmail.com', 'fecha_nacimiento' => '1979-06-06', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'Julian Andres', 'apellidos' => 'Chimbi giraldo', 'cedula' => '1069750812', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'GTU544', 'numero_interno' => '787', 'celular' => '3167714152', 'correo' => 'andresgiraldors@gmail.com', 'fecha_nacimiento' => '1995-04-01', 'otra_profesion' => 'Psicólogo', 'nivel_estudios' => 'Profesional' ],
[ 'nombres' => 'Elías', 'apellidos' => 'García Cuéllar', 'cedula' => '93471125', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'TTX502', 'numero_interno' => '766', 'celular' => '3117048969', 'correo' => 'elias72cuellargmail.com', 'fecha_nacimiento' => '1972-05-29', 'otra_profesion' => 'Oficios varios', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'José Omar', 'apellidos' => 'Rodríguez mican', 'cedula' => '11436419', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'TGT937', 'numero_interno' => '737', 'celular' => '3146243306', 'correo' => 'andavid2010@hotmail.com', 'fecha_nacimiento' => '1968-08-22', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'Vladimir', 'apellidos' => 'Torres esterling', 'cedula' => '4438613', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'THP548', 'numero_interno' => '777', 'celular' => '3142386852', 'correo' => 'No tiene', 'fecha_nacimiento' => '1984-04-17', 'otra_profesion' => 'Mecánico', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'Diego Alberto', 'apellidos' => 'Moreno Linares', 'cedula' => '80283602', 'conductor_tipo' => 'B', 'rh' => 'O+', 'vehiculo_placa' => 'WFW142', 'numero_interno' => '1060', 'celular' => '3218221350', 'correo' => 'diegomli350@gmail.com', 'fecha_nacimiento' => '1984-10-13', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'Luis Alberto', 'apellidos' => 'Londoño Cardona', 'cedula' => '16115576', 'conductor_tipo' => 'B', 'rh' => 'O+', 'vehiculo_placa' => 'RELEVO', 'numero_interno' => 'Relevo', 'celular' => '3106167191', 'correo' => 'londonoluis345@gmail.com', 'fecha_nacimiento' => '1985-03-12', 'otra_profesion' => 'No', 'nivel_estudios' => 'Hasta primaria' ],
[ 'nombres' => 'José Ricardo', 'apellidos' => 'Jaramillo Aguirre', 'cedula' => '1002643379', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'SPE059', 'numero_interno' => '707', 'celular' => '3193429771', 'correo' => 'josericardojaramilloaguirre27@gmail.com', 'fecha_nacimiento' => '1995-10-27', 'otra_profesion' => 'Oficios varios', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'Brayan Antonio', 'apellidos' => 'Martínez Moreno', 'cedula' => '1105783734', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'WBH047', 'numero_interno' => '692', 'celular' => '3116919343', 'correo' => 'brayanmartinez@hotmail.com', 'fecha_nacimiento' => '1988-08-08', 'otra_profesion' => 'Mecánico', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'José Fidel', 'apellidos' => 'Castillo Hernández', 'cedula' => '14321960', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'TZR533', 'numero_interno' => '1070', 'celular' => '3108580764', 'correo' => 'josefidel443@gmail.com', 'fecha_nacimiento' => '1971-04-26', 'otra_profesion' => 'Constructor', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'Jhon mediz', 'apellidos' => 'Tangarife escobar', 'cedula' => '15991646', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'STP689', 'numero_interno' => '757', 'celular' => '3128119011', 'correo' => 'jhonmediztangarifeescobar@gmal.com', 'fecha_nacimiento' => '1984-05-02', 'otra_profesion' => 'No', 'nivel_estudios' => 'Hasta primaria' ],
[ 'nombres' => 'Yezid', 'apellidos' => 'Gonzales Romero', 'cedula' => '80012589', 'conductor_tipo' => 'B', 'rh' => 'O+', 'vehiculo_placa' => 'WCW472', 'numero_interno' => '980', 'celular' => '3148292203', 'correo' => 'No tiene', 'fecha_nacimiento' => '1980-08-27', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'Fabio Nelson', 'apellidos' => 'Jiménez Reyes', 'cedula' => '15990719', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'GTT914', 'numero_interno' => '775', 'celular' => '3207000459', 'correo' => 'fabio.nel@gmail.com', 'fecha_nacimiento' => '1980-12-10', 'otra_profesion' => 'No', 'nivel_estudios' => 'Hasta primaria' ],
[ 'nombres' => 'Ramiro', 'apellidos' => 'Valencia Osorio', 'cedula' => '159881243', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'WHU535', 'numero_interno' => '772', 'celular' => '3217108180', 'correo' => 'No tiene', 'fecha_nacimiento' => '1970-03-10', 'otra_profesion' => 'Agricultor', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'Pedro Luis', 'apellidos' => 'Guzmán Madrid', 'cedula' => '10172108', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'SVF964', 'numero_interno' => '691', 'celular' => '3122144136', 'correo' => 'pedronilguzman@gmail.com', 'fecha_nacimiento' => '1966-03-09', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'fernando alfonso', 'apellidos' => 'valdez lopez', 'cedula' => '10189215', 'conductor_tipo' => 'A', 'rh' => 'AB+', 'vehiculo_placa' => 'SCK140', 'numero_interno' => '697', 'celular' => '3103565981', 'correo' => 'fernandovaldezlopez1982@gmail.com', 'fecha_nacimiento' => '1982-02-22', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'jose tomas', 'apellidos' => 'giraldo ramirez', 'cedula' => '80071653', 'conductor_tipo' => 'B', 'rh' => 'O+', 'vehiculo_placa' => 'SVM071', 'numero_interno' => '860', 'celular' => '3158161436', 'correo' => 'jochoramirez2437@gmail.com', 'fecha_nacimiento' => '1981-11-07', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'jose alexander', 'apellidos' => 'rusinque', 'cedula' => '4438284', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'SXE810', 'numero_interno' => '764', 'celular' => '3103868919', 'correo' => 'no tiene', 'fecha_nacimiento' => '1983-11-24', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'victor adrian', 'apellidos' => 'perez isaza', 'cedula' => '1096215736', 'conductor_tipo' => 'B', 'rh' => 'O+', 'vehiculo_placa' => 'EQZ530', 'numero_interno' => '1015', 'celular' => '3233225744', 'correo' => 'coopuertos1015@gmail.com', 'fecha_nacimiento' => '1991-10-30', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'jose fernando', 'apellidos' => 'arroyabe lopez', 'cedula' => '10268853', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'RELEVO', 'numero_interno' => 'relevo', 'celular' => '3104403441', 'correo' => 'no tiene', 'fecha_nacimiento' => '1964-01-09', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'leonardo', 'apellidos' => 'montaño rodriguez', 'cedula' => '11522682', 'conductor_tipo' => 'A', 'rh' => 'AB+', 'vehiculo_placa' => 'UPB331', 'numero_interno' => '784', 'celular' => '3118463955', 'correo' => 'leomontano632@gmail.com', 'fecha_nacimiento' => '1977-08-24', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'Deidyn eduardo', 'apellidos' => 'castillo rodriguez', 'cedula' => '80200862', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'TTZ397', 'numero_interno' => '716', 'celular' => '3205215236', 'correo' => 'ec0246549@gmail.com', 'fecha_nacimiento' => '1981-03-01', 'otra_profesion' => 'No', 'nivel_estudios' => 'Hasta primaria' ],
[ 'nombres' => 'alexander', 'apellidos' => 'echeverry', 'cedula' => '16075095', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'WNZ662', 'numero_interno' => '749', 'celular' => '3006604291', 'correo' => 'echeverryalexander988@gmail.com', 'fecha_nacimiento' => '1980-07-07', 'otra_profesion' => 'electrisista', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'jorge orlando', 'apellidos' => 'vergara castro', 'cedula' => '70137605', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'SPE021', 'numero_interno' => '699', 'celular' => '3226493924', 'correo' => 'jorgevergara.cas@gmail.com', 'fecha_nacimiento' => '1972-11-11', 'otra_profesion' => 'No', 'nivel_estudios' => 'Hasta primaria' ],
[ 'nombres' => 'julian camilo', 'apellidos' => 'ospina valencia', 'cedula' => '1007619013', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'TTZ772', 'numero_interno' => '727', 'celular' => '3145268324', 'correo' => 'julcaospiva@hotmail.com', 'fecha_nacimiento' => '2000-11-29', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'ruben dario', 'apellidos' => 'luna donato', 'cedula' => '80824821', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'WEV209', 'numero_interno' => '769', 'celular' => '3183927104', 'correo' => 'chiquitica4282@hotmail.com', 'fecha_nacimiento' => '1984-01-10', 'otra_profesion' => 'oficios varios', 'nivel_estudios' => 'Profesional' ],
[ 'nombres' => 'fabio ivan', 'apellidos' => 'vargas castro', 'cedula' => '93419864', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'STR270', 'numero_interno' => '776', 'celular' => '3248696379', 'correo' => 'ivanvargascastro9@gmail.com', 'fecha_nacimiento' => '1976-11-14', 'otra_profesion' => 'No', 'nivel_estudios' => 'Hasta primaria' ],
[ 'nombres' => 'yeider alejandro', 'apellidos' => 'ocampo aristizabal', 'cedula' => '1007429094', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'WPR579', 'numero_interno' => '774', 'celular' => '3205345218', 'correo' => 'yeiderocampo68@gmail.com', 'fecha_nacimiento' => '1996-06-25', 'otra_profesion' => 'No', 'nivel_estudios' => 'Hasta primaria' ],
[ 'nombres' => 'hernando', 'apellidos' => 'rodriguez navas', 'cedula' => '10174736', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'GTU282', 'numero_interno' => '778', 'celular' => '3145973657', 'correo' => 'hernandorodriguez1569@gmail.com', 'fecha_nacimiento' => '1969-01-15', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'hector adan', 'apellidos' => 'ibagon', 'cedula' => '10168080', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'UFU915', 'numero_interno' => '698', 'celular' => '3128252104', 'correo' => 'no tiene', 'fecha_nacimiento' => '1962-05-15', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'mauricio', 'apellidos' => 'garcia lopez', 'cedula' => '75079538', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'STQ986', 'numero_interno' => '781', 'celular' => '3218810501', 'correo' => 'mauricioglopez25@gmail.com', 'fecha_nacimiento' => '1976-01-25', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'jhon fernando', 'apellidos' => 'ramirez gutierrez', 'cedula' => '9858894', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'ETO544', 'numero_interno' => '787', 'celular' => '3118097445', 'correo' => 'kafir200612@gmail.com', 'fecha_nacimiento' => '1979-08-08', 'otra_profesion' => 'tecnico aeronautico', 'nivel_estudios' => 'Tecnologo' ],
[ 'nombres' => 'luis mario', 'apellidos' => 'ospina marin', 'cedula' => '15988919', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'TTHP225', 'numero_interno' => '788', 'celular' => '3113361138', 'correo' => 'ospinamarinluismario3@gmail.com', 'fecha_nacimiento' => '1972-12-12', 'otra_profesion' => 'comerciante', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'yeison andres', 'apellidos' => 'ramos ospina', 'cedula' => '1030561164', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'NOK703', 'numero_interno' => '798', 'celular' => '3135240842', 'correo' => 'yeisonandres21@hotmail.com', 'fecha_nacimiento' => '1989-08-10', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'estevan', 'apellidos' => 'celis ruiz', 'cedula' => '10189748', 'conductor_tipo' => 'A', 'rh' => 'A+', 'vehiculo_placa' => 'SVM691', 'numero_interno' => '744', 'celular' => '3114029318', 'correo' => 'yojuan2206@gmail.com', 'fecha_nacimiento' => '1982-06-22', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'LUIS ALBERTO', 'apellidos' => 'CASTAÑO ALZATE', 'cedula' => '10175201', 'conductor_tipo' => 'B', 'rh' => 'A+', 'vehiculo_placa' => 'RELEVO', 'numero_interno' => 'RELEVO', 'celular' => '3137686391', 'correo' => 'luisalbertocastanoalzate6@gmail.com', 'fecha_nacimiento' => '1969-06-07', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'jhon jairo', 'apellidos' => 'velasquez morales', 'cedula' => '98587221', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'SPE021', 'numero_interno' => '699', 'celular' => '3117974083', 'correo' => 'jairovelasquez648@gmail.com', 'fecha_nacimiento' => '1972-07-06', 'otra_profesion' => 'No', 'nivel_estudios' => 'Hasta primaria' ],
[ 'nombres' => 'frankin', 'apellidos' => 'agulera diagama', 'cedula' => '79865941', 'conductor_tipo' => 'B', 'rh' => 'AB+', 'vehiculo_placa' => 'EQZ530', 'numero_interno' => '1015', 'celular' => '3204896281', 'correo' => 'frankaguidia@hotmail.com', 'fecha_nacimiento' => '1977-08-07', 'otra_profesion' => 'oficios varios', 'nivel_estudios' => 'Tecnologo' ],
[ 'nombres' => 'leo steve', 'apellidos' => 'ospina jimenes', 'cedula' => '80801819', 'conductor_tipo' => 'B', 'rh' => 'O+', 'vehiculo_placa' => 'RELEVO', 'numero_interno' => 'relevo', 'celular' => '3243663125', 'correo' => 'ospinajimenesleosteve@gmail.com', 'fecha_nacimiento' => '1984-11-25', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'Joaquin jovany', 'apellidos' => 'Pérez Sánchez', 'cedula' => '77166319', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'ESS501', 'numero_interno' => '767', 'celular' => '3105227689', 'correo' => 'giovanyp570@gmail.com', 'fecha_nacimiento' => '1976-08-01', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'anadres', 'apellidos' => 'vasquez useche', 'cedula' => '80167725', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'ETM119', 'numero_interno' => '773', 'celular' => '3133669569', 'correo' => 'andresenvasquez@hotmail.com', 'fecha_nacimiento' => '1981-12-24', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'ciro amadeo', 'apellidos' => 'jimenez garzon', 'cedula' => '80376927', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'KZW600', 'numero_interno' => '1075', 'celular' => '3133010531', 'correo' => 'ciroamadeojimenezgarzon@gmail.com', 'fecha_nacimiento' => '1974-11-27', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller' ],
[ 'nombres' => 'jose alfredo', 'apellidos' => 'ramirez laverde', 'cedula' => '1128627330', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'STQ488', 'numero_interno' => '765', 'celular' => '3024474822', 'correo' => 'laverdej089@gmail.com', 'fecha_nacimiento' => '1995-08-13', 'otra_profesion' => 'oficios varios', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'Robinson', 'apellidos' => 'Orozco López', 'cedula' => '1054555687', 'conductor_tipo' => 'B', 'rh' => 'O+', 'vehiculo_placa' => 'SCK169', 'numero_interno' => '935', 'celular' => '3113652359', 'correo' => 'robinson90129@gmail.com', 'fecha_nacimiento' => '1991-09-23', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'gerardo alonso', 'apellidos' => 'castrillon quiceno', 'cedula' => '15987059', 'conductor_tipo' => 'A', 'rh' => 'O+', 'vehiculo_placa' => 'TTX765', 'numero_interno' => '711', 'celular' => '3206111222', 'correo' => 'NO TIENE', 'fecha_nacimiento' => '1964-04-21', 'otra_profesion' => 'SI; OFICIAL DE CONTRUCCION', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'RICARDO', 'apellidos' => 'GARZON CIFUENTES', 'cedula' => '79782855', 'conductor_tipo' => 'B', 'rh' => 'B+', 'vehiculo_placa' => 'RELEVO', 'numero_interno' => 'RELEVO', 'celular' => '3102614300', 'correo' => 'ricardogarcia1970@gmail.com', 'fecha_nacimiento' => '1970-07-19', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller sin terminar' ],
[ 'nombres' => 'climaco andres', 'apellidos' => 'garzon cifuentes', 'cedula' => '80500310', 'conductor_tipo' => 'B', 'rh' => 'B+', 'vehiculo_placa' => 'WCW628', 'numero_interno' => '1065', 'celular' => '3137930202', 'correo' => 'anndress1974@hotmail.com', 'fecha_nacimiento' => '1974-08-19', 'otra_profesion' => 'No', 'nivel_estudios' => 'Bachiller sin terminar' ],
];


       foreach ($data as $row) {
    Conductor::create($row);
}
    }
}